Problem - @total_batches + 1 -> NoMethodError: undefined method `+' for nil:NilClass - In test/integration/shared_blog_posts_feed_test.rb:38:
Where

- test/integration/shared_blog_posts_feed_test.rb:38:
	- @total_batches + 1

What

- NoMethodError: undefined method `+' for nil:NilClass
> CLI: rails t test/integration/shared_blog_posts_feed_test.rb
```
ERROR["test_Should_HAVE", #<Minitest::Reporters::Suite:0x00007fecf2116db8 @name="SharedBlogPostsFeedTest">, 4.115155999999843]
 test_Should_HAVE#SharedBlogPostsFeedTest (4.12s)
NoMethodError:         NoMethodError: undefined method `+' for nil:NilClass
            test/integration/shared_blog_posts_feed_test.rb:38:in `block in <class:SharedBlogPostsFeedTest>'

```
Input
> app/controllers/static_pages_controller.rb
- @total_batches is Defined
  @total_batches = calculate_total_batches(batch_size)
```
class StaticPagesController < ApplicationController
  include CalculateTotalBatchesHelper
  include CalculateTotalBatchesHelper

  def home
    batch_size = 100
    @total_batches = calculate_total_batches(batch_size)
    @blog_posts_feed = fetch_blog_posts_as_a_batch(params[:direction], params[:clicked_page], batch_size)

    if logged_in?
      @blog  = current_user.blogs.build
    end

  end
...
```

> test/integration/shared_blog_posts_feed_test.rb:38:
```
  # - Blog Post Feed is SHA.RED
require 'test_helper'

class SharedBlogPostsFeedTest < ActionDispatch::IntegrationTest
...

  test "Should HAVE" do
    log_in_as(@user)
    get root_path
...
      # Each Feed Button
        # First page
          # fetch_blog_posts_as_a_batch(nil, nil, "100")
          # define_batch_size
          # @total_batches = calculate_total_batches(100)
          @feed_button_amount = @total_batches + 1
            # One for each batch + Next
          assert_select 'a.feed-button', count: @feed_button_amount
        # Second page
          get root_path(params: { clicked_page: "2" })
          @feed_button_amount = @total_batches + 2
            # One for each batch + Next + Previous

          assert_select 'a.feed-button', count: @feed_button_amount

  end
```