Try.4 - Add session for feed start and finish - Use in in_batches
Purpose

- Allow infinite automated fetching of ALL blog posts
	=> Solve the problem

Output

- Session is SET as I meant

	P
	- : DokoDemon: Problem (2021.12.22): => Test.4 - Add session for feed start and finish - Use in in_batches -

> CLI

> rails t
- At app/controllers/static_pages_controller.rb:5:in `home'
	- Error: MethodError: undefined method `paginate' for #<ActiveRecord::Batches::BatchEnumerator
- At  test/helpers/blog_posts_feed_helper_test.rb:23:in `block (2 levels) in <class:BlogPostsFeedHelperTest>' | test_NO_login_=>_Should_show_all_posts
test_NO_login_=>_Should_show_all_posts", #<Minitest::Reporters::Suite:0x00007fafe159da60 @name="BlogPostsFeedHelperTest">, 9.65432200000032]
        Expected false to be truthy.
```
Blog.all.each do |blog_post|
        assert @blog_posts_feed.include?(blog_post)
      end
```